### ISSUE TITLE
Installation on Synology DSM

### ISSUE THREAD

**Issue by luckiestone** [kz26/dottorrent-gui#40]
Hello, I've install the Python3, pip, and PyQt5 on my Synology DS918+. dottorrent was installed with no issue, but when I run it, and error shows:
```
root@DS918Plus:~# dottorrent-gui
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/bin/dottorrent-gui", line 5, in <module>
    from dottorrentGUI.gui import main
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/dottorrentGUI/__init__.py", line 1, in <module>
    from .ui_mainwindow import Ui_MainWindow
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/dottorrentGUI/ui_mainwindow.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
I don't know where to find ligGL.so.1 and how to install it on DSM, which may solve this issue.

**Comment by kz26** [comment]
Hello, are you running a GUI on a Synology NAS via a remote X session or something similar? It appears DSM does not have a full Mesa/libGL stack. Since this is highly vendor-specific I will be closing this issue.
